#! /usr/bin/env bash

# pain-get <url> <tags> <color>

if [[ $# < 2 ]]; then
    echo "Error: Wrong number of Arguments"
    exit 1
fi

ARGV=()

while [[ $# -gt 0 ]]; do
  case $1 in
    *)
      ARGV+=("$1") # save positional arg
      ;;
  esac
  shift
done

DIR="$HOME/Wallpaper"
DWM_COLORS="$HOME/.config/dwm/colors"


URL="${ARGV[0]}"
TAGS="${ARGV[1]}"

FILE=$(date +"%s")
FILE="$FILE.${URL##*.}"

wget "$URL" -O "$FILE"
wait

update_dwm() {
    echo "$COLOR"  >  "$DWM_COLORS"
    echo "#1b1b1b" >> "$DWM_COLORS"
    echo "#1b1b1b" >> "$DWM_COLORS"
    echo "#1b1b1b" >> "$DWM_COLORS"
    echo "$COLOR"  >> "$DWM_COLORS"
    echo "$COLOR"  >> "$DWM_COLORS"
    dwm-refresh
}

feh --bg-fill "$FILE"

while true; do
    read -p "pick, exit, <hexcolor>, add: " INPUT

    case $INPUT in 
        pick )
            eval $(xdotool getmouselocation --shell)
            IMAGE=`import -window root -depth 8 -crop 1x1+$X+$Y txt:-`
            COLOR=`echo $IMAGE | grep -om1 '#\w\+'`
            update_dwm
            ;;
        add ) 
            ADD=1
            break
            ;;
        exit ) 
            break
            ;;
        * ) 
            if [[ $INPUT =~ ^#[0-9A-Fa-f]{6}$ ]] ; then
                COLOR=$INPUT
                update_dwm
            else
                echo "invalid response"
            fi
            ;;
    esac
done

if [ "$ADD" ]; then
    echo "Adding $FILE to $DIR"
    ficor --config "${DIR}/.ficor" --add-file "$FILE" -t "$TAGS" --set-info "$COLOR"
    FILE="$(pwd)/$FILE"
    cd "$DIR"
    cp -f "$FILE" "."
fi

rm -f "$FILE"
